# Generated by Django 3.0.4 on 2020-08-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keys',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='key')),
                ('shortkey', models.CharField(max_length=8, verbose_name='short key')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('environment', models.CharField(max_length=125, verbose_name='omgeving')),
                ('seen', models.CharField(max_length=48, verbose_name='opgehaald')),
                ('start_timestamp', models.CharField(max_length=48, verbose_name='timestamp start')),
                ('end_timestamp', models.CharField(max_length=48, verbose_name='timestamp end')),
                ('num_teks', models.IntegerField(verbose_name='number of keys')),
            ],
            options={
                'verbose_name': 'Exposure Keyset',
                'verbose_name_plural': 'Exposure Keysets',
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_trl_1', models.IntegerField(verbose_name='sum trl 1')),
                ('sum_trl_2', models.IntegerField(verbose_name='sum trl 2')),
                ('sum_trl_3', models.IntegerField(verbose_name='sum trl 3')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keys.Keys')),
            ],
            options={
                'verbose_name': 'Statistieken',
                'verbose_name_plural': 'Statistieken',
            },
        ),
    ]
